
baseurl = "https://dorajam.github.io/thoughts/"
publishdir = "public"
layoutdir = "layouts"
contentdir = "content/post"
canonifyurls = true
hasmath = true


Languagecode = "en-us"
title = "DORA JAMBOR"
theme = "detox"
disqusShortname = "http-dorajam-github-io-thoughts"

[params]
  description = "Things that tickle my mind"
  author = "Dora Jambor"
  disqusShortname = "@dorajambor"

[taxonomies]
  category = "categories"
  tag = "tags"
